function maskMap()

    % Create a Mask volume.
    mask_vol = deal(struct(...
      'fname',    fullfile(fileparts(mfilename('fullpath')), 'data',...
                           'mask.nii'),...
      'dim',      [91 109 91],...
      'dt',       [spm_type('float32') spm_platform('bigend')],...
      'mat',      eye(4),...
      'pinfo',    [1 0 0]',...
      'descrip',  'Mask showing area bias was induced in'));
    mask_vol = spm_create_vol(mask_vol);
    
    % Make the mask.
    mask = zeros(91, 109, 91);
    mask(50:53, 50:53, 50:53) = 1;
    
    % Save the mean map.
    spm_write_vol(mask_vol, mask);

end